[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nlp_pipeline"
version = "0.1.0"
authors = ["Alessio Salati"]
readme = "README.md"
license = "MIT"

[tool.setuptools]
package-dir = {"" = "src"}
